#!/bin/bash

toplevel=$(git rev-parse --show-toplevel)

git_dir=$(git rev-parse --git-dir)

script_path='hooks/script/auto-cop'

echo "Cleaning your commit with rubocop --auto-correct"

exec "$toplevel/$git_dir/$script_path"
