git submodule add https://github.com/mileszs/ack.vim.git vimfiles/bundle/ack.vim
git submodule add https://github.com/vim-scripts/BufOnly.vim.git vimfiles/bundle/BufOnly.vim
git submodule add https://github.com/vim-scripts/Color-Sampler-Pack.git vimfiles/bundle/Color-Sampler-Pack
git submodule add https://github.com/kien/ctrlp.vim.git vimfiles/bundle/ctrlp.vim
git submodule add https://github.com/Raimondi/delimitMate.git vimfiles/bundle/delimitMate
git submodule add https://github.com/sjl/gundo.vim.git vimfiles/bundle/gundo.vim
git submodule add https://github.com/twerth/ir_black.git vimfiles/bundle/ir_black
git submodule add https://github.com/wookiehangover/jshint.vim vimfiles/bundle/jshint
git submodule add https://github.com/vim-scripts/moria.git vimfiles/bundle/moria
git submodule add https://github.com/scrooloose/nerdtree.git vimfiles/bundle/nerdtree
git submodule add https://github.com/vim-scripts/ScrollColors.git vimfiles/bundle/ScrollColors
git submodule add https://github.com/SirVer/ultisnips.git vimfiles/bundle/ultisnips
git submodule add https://github.com/tpope/vim-abolish.git vimfiles/bundle/vim-abolish
git submodule add https://github.com/bling/vim-airline.git vimfiles/bundle/vim-airline
git submodule add https://github.com/kchmck/vim-coffee-script.git vimfiles/bundle/vim-coffee-script
git submodule add https://github.com/altercation/vim-colors-solarized.git vimfiles/bundle/vim-colors-solarized
git submodule add https://github.com/tpope/vim-commentary.git vimfiles/bundle/vim-commentary
git submodule add https://github.com/Lokaltog/vim-easymotion.git vimfiles/bundle/vim-easymotion
git submodule add https://github.com/digitaltoad/vim-jade.git vimfiles/bundle/vim-jade
git submodule add https://github.com/jelera/vim-javascript-syntax.git vimfiles/bundle/vim-javascript-syntax
git submodule add https://github.com/maksimr/vim-jsbeautify.git vimfiles/bundle/vim-jsbeautify
git submodule add https://github.com/elzr/vim-json.git vimfiles/bundle/vim-json
git submodule add https://github.com/groenewege/vim-less.git vimfiles/bundle/vim-less
git submodule add https://github.com/jistr/vim-nerdtree-tabs.git vimfiles/bundle/vim-nerdtree-tabs
git submodule add https://github.com/tpope/vim-pathogen.git vimfiles/bundle/vim-pathogen
git submodule add https://github.com/honza/vim-snippets.git vimfiles/bundle/vim-snippets
git submodule add https://github.com/wavded/vim-stylus.git vimfiles/bundle/vim-stylus
git submodule add https://github.com/tpope/vim-surround.git vimfiles/bundle/vim-surround
git submodule add https://github.com/tomasr/molokai.git vimfiles/bundle/molokai
