#!/usr/bin/env zsh
# vi: ft=zsh

function psql_grant_priveleges() {
  if [[ -z "$POSTGRES_CONNECTION_STRING" ]]; then
    echo 1>&2 "Must export POSTGRES_CONNECTION_STRING"
    return 1
  fi

  if [[ -z $1 ]]; then
    echo 1>&2 "Must specify a user"
    echo 1>&2 "  e.g. members_svc"
    return 1
  fi

  local database_user="$1"
  psql "$POSTGRES_CONNECTION_STRING" << SQL
    ALTER ROLE $database_user WITH SUPERUSER
SQL
}
