#!/usr/bin/env zsh
# vi: ft=zsh

# Safely, idempotently, append to path
function append_to_path() {
  local d
  for d; do
    d=$(cd -- "$d" && { pwd -P || pwd; }) 2>/dev/null # canonicalize symbolic links (? what?)
    if [ -z "$d" ]; then continue; fi # skip nonexistent directory

    # Append to the path
    # NOTE: because of 'typeset -U path' set in zsh/config this won't relocate an
    #   existing entry to the end of the path, it'll just cease to exist as the right-most
    #   duplicate is removed.
    path=($path $d)
  done
}

