#!/usr/bin/env zsh
# vi: ft=zsh

function git_show_exclude_ruby_files() {
    # Takes the list of files from git-show AM and removes excluded files with grep.
    git_show AM \
        | grep \.rb$ \
        | grep -vE -e 'routes\.rb|schema\.rb|\.html\.erb|\.yml|Gemfile|Gemfile\.lock|\.json'
}
