#!/usr/bin/env zsh
# vi: ft=zsh

# Output a pretty, oneline, columnized, git log for the last twenty commits
function git_pretty_log() {
  local log_count=${1:-20}
  local line_wrap='%w(87,0,6)'

  local red_short_hash='%Cred%h%Creset'

  local truncation_amount=51
  local truncated_message="%<($truncation_amount,trunc)%s"

  local truncate_date='%<(10,trunc)'
  local blue_date="%Cblue$truncate_date%cr%Creset"

  local truncate_name='%<(12,trunc)'
  local green_name="%Cgreen$truncate_name%an%Creset"

  local yellow_refs='%C(yellow)%D%Creset'

  local format_string="$line_wrap$red_short_hash - $truncated_message $blue_date $green_name $yellow_refs"

  git log -$log_count --pretty=format:$format_string --abbrev-commit --date=relative
}
