#!/usr/bin/env zsh
# vi: ft=zsh

function git_me() {
  local github_path=$1

  local author=${github_path%/*}
  local plugin=${github_path#*/}

  # Default the author if we didn't provide one
  if [[ $author == $plugin ]]; then
    author='trunkclub'
  fi

  local repository="git@github.com:$author/$plugin.git"

  local directory=~/dev/$plugin

  if [[ -d "$directory" ]]; then
    echo 1>&2 "$plugin already exists, changing directory"
    cd "$directory"
    return 0
  fi

  git clone $repository $directory && cd $directory
}
