#!/usr/bin/env zsh
# vi: ft=zsh

# This function rewrites _everythign_ in your current repo to change their
# authors. It does not change the commit or author date
#
# Source: https://help.github.com/en/articles/changing-author-info
function git_rewrite_authors() {
  echo "Make sure to manually edit the zsh function to get your emails set up"

  local for_real="$1"
  if [[ "$for_real" != "--for-real" ]]; then
    echo 1>&2 "You have not specified '--for-real'. Run with that flag to do the rewriting"
    return 1
  fi

  git config user.name "Trent Scheffert"
  git config user.email "trent.scheffert@echo.com"

  git filter-branch --force --env-filter '
  OLD_EMAIL="trent.scheffert@gmail.com"
  CORRECT_NAME="Trent Scheffert"
  CORRECT_EMAIL="trent.scheffert@echo.com"

  if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
  then
      export GIT_COMMITTER_NAME="$CORRECT_NAME"
      export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
  fi
  if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
  then
      export GIT_AUTHOR_NAME="$CORRECT_NAME"
      export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
  fi
  ' --tag-name-filter cat -- --branches --tags
}
