#!/usr/bin/env zsh
# vi: ft=zsh

# With <3 from http://stackoverflow.com/a/15135004/2675529, for use with
# https://saintgimp.org/2013/01/22/merging-two-git-repositories-into-one-repository-without-losing-file-history/
function historical_git_mv() {
  function usage() {
    echo 1>&2
    echo 1>&2 "Usage:"
    echo 1>&2 "  historical_git_mv SOURCE DESTINATION"
  }

  local failure
  local source="$1"
  if [[ -z "$source" ]]; then
    echo 1>&2 "Must specify SOURCE file"
    failure=true
  fi

  local destination="$2"
  if [[ -z "$destination" ]]; then
    echo 1>&2 "Must specify DESTINATION directory"
    failure=true
  fi

  if [[ -n "$destination" && -f "$destination" ]]; then
    echo 1>&2 "DESTINATION must be a directory"
    failure=true
  fi

  if [[ "$failure" ]]; then
    usage
    return 1
  fi

  echo "Rewriting history to move $source to $destination/"

  git filter-branch --tree-filter \
    "if [ -f $source ]; then mkdir -p $destination && mv $source $destination/$source; fi" \
    HEAD
}
