#!/usr/bin/env zsh
# vi: ft=zsh

# Takes a package to add to Echo's nuget external
function nuget_add_external() {
  local package="${1:?You must specify a package to add}"

  local escaped_source="\\\\devops.echo.com\\g\$\\NuGet\\External"
  C:/tools/nuget/nuget.exe add "$package"  -source "$escaped_source"
}

nuget_add_external "$@"
