#!/usr/bin/env zsh
# vi: ft=zsh

# Safely, idempotently, prepend to path
function prepend_to_path() {
  local d
  for d; do
    d=$(cd -- "$d" && { pwd -P || pwd; }) 2>/dev/null # canonicalize symbolic links (? what?)
    if [ -z "$d" ]; then continue; fi # skip nonexistent directory
    path=($d $path) # add it to the front of the path array
  done
}
