#!/usr/bin/env zsh
# vi: ft=zsh

# With <3 from: https://thomas-barthelemy.github.io/2015/10/31/git-aliases/

# Convert a '~/.dotfiles/thing' path to 'C:\Users\tscheffert\.dotfiles\thing'
function to_windows_path() {
  if [ ${#} -eq 0 ]; then
    : skip
  elif [ -f "$1" ]; then
    local dirname=$(dirname "$1")
    local basename=$(basename "$1")
    echo "$(cd "$dirname" && pwd -W)/$basename" \
    | sed \
      -e 's|/|\\|g';
  elif [ -d "$1" ]; then
    echo "$(cd "$1" && pwd -W)" \
    | sed \
      -e 's|/|\\|g';
  else
    echo "$1" \
    | sed \
      -e 's|^/\(.\)/|\1:\\|g' \
      -e 's|/|\\|g'
  fi
}
