#!/usr/bin/env zsh
# vi: ft=zsh

# Easily search for things in the zshman pages
# From: http://chneukirchen.org/blog/archive/2012/02/10-new-zsh-tricks-you-may-not-know.html
function zman() {
  PAGER="less -g -s '+/^       "$1"'" man zshall
}
