#!/usr/bin/env zsh
# vi: ft=zsh

# Folder shortcuts
alias cd-d='cd ~/.dotfiles'
alias cd-dev='cd ~/dev'

# ls alias for color-mode
alias lh='ls -lhaG'

# Prompt me if deleting more than three files or doing it recursively
alias rm='rm -I'

# simple ip
# TODO: Right now this fails, saying "cut: bad delimiter"
# alias ip='ifconfig | grep "inet " | grep -v 127.0.0.1 | cut -d\ -f2'

# more details
# TODO: This works, but not sure what it means...
# alias ip1="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"

# external ip
# TODO: Fix this, getting external IP would be awesome. Right now it just hangs
# alias ip2="curl -s http://www.showmyip.com/simple/ | awk '{print $1}'"

# See hidden files with ls
alias ls="ls -a --color=always"

# Hidden files for the_silver_searcher
alias ag="ag --hidden"

# grep with color
# for whatever reason this doesn't work with my grep on windows
#alias grep='grep --color=auto'
alias grep='grep -i'

# refresh shell
alias reload='exec zsh -l'

# -- Postgres Aliases --

alias pg-start='pg_ctl -l $PGDATA/server.log start'
alias pg-stop='pg_ctl stop -m fast'
alias pg-status='pg_ctl status'
alias pg-restart='pg_ctl reload'

# Run psql for my local instance
alias pg-local='psql postgres://trunkclub:trunkclub@192.168.23.2/postgres'

# -- Git Aliases --

# Standard!
alias g='git'

# status!
alias gs='git status'

alias ga='git add'

alias gb='git branch'

# Git branch all
alias gba='git branch -a'

# Git branch delete
alias gbd='git branch -d'

# Git branch move (renames the branch to the supplied reflog)
alias gbm='git branch -m'

# Git branch force delete
alias gbfd='git branch -D'

# Grant branch delete --merged
alias gbd-m='git_delete_merged'

# List the recent git branches
alias gbr='git_branch_recent'

# Git add patched
alias gap='git add -p'

# Git add all
alias gaa='git add .'

# Git add all (and) commit
alias gaac='git add . && git commit'

# Git add only updated files, no new files
alias gau='git add -u'

# Git add new, adds a blank file for untracked files, useful for things like git diff
alias gan='git add -N'

# Git commit
alias gc='git commit'

# Git commit with message
alias gcm='git commit -m'

# --amend changes the latest commit, and --no-edit tells it we don't want to change the messge
alias gca='git commit --amend --no-edit'

# Git commit amend message
alias gcam='git commit --amend'

# Git commit ammend, with edit (the message)
alias gcae='git commit --amend'

alias gd='git diff --color-words'

alias gds='git diff --staged --color-words'

# Git diff (with) origin master
alias gdom='git diff origin/master..'

alias gp='git pull'

# Git force push, --force-with-lease ensures that we have the latest info from origin before allowing the force
alias gfpu='git push --force-with-lease'

alias gpu='git push'

alias gco='git checkout'

alias gcom='git checkout master'

# Git checkout all
alias gcoa='git checkout -- .'

# Follow it up with a hyphen delimited branch name like: 'gcob my-branch-name'
alias gcob='git checkout -b'

alias glg='git_pretty_log'

# Show the diffs for recent commits with git log
alias glp='git log -p'

# Git log files, shows all the files in each commit and how much they've changed
alias glf='git log --stat --oneline origin/master..HEAD'

alias gr='git rebase'

alias grc='git rebase --continue'

alias gra='git rebase --abort'

alias grom='git rebase origin/master'

alias griom='git rebase -i origin/master'

# Git reset to head
alias grs='git reset HEAD'

# Undo the last commit(s)
alias grh1='git reset HEAD~1'
alias grh2='git reset HEAD~2'
alias grh3='git reset HEAD~3'

# Temporarily ignore changes but leave them in the filesystem
#   'git ignore add', follow up with a <file>
alias gi-a='git update-index --assume-unchanged'

# Stop ignoring a file
#   'git ignore remove'
alias gi-r='git update-index --no-assume-unchanged'

# List all ignored files
#   'git ignore list'
alias gi-l="git ls-files -v | grep '^[[:lower:]]' | cut -f2 -d' '"

# Git Branch Fix Upstream
alias gbfu="git branch --set-upstream-to=origin/$(git symbolic-ref --quiet --short HEAD 2>/dev/null)"

# Git Branch Previous
alias gbrp='git reflog | sed -n "s/.*checkout: moving from .* to \(.*\)/\1/p" | sed "2q;d"'

# Git show
alias gsh='git show'

# Stash all tracked, unstaged files
alias gst='git stash'

# Stash with a message, includes untracked and ignored files
alias gssa='git stash save --include-untracked'

# Git stash save with patch
alias gssap='git stash save --patch'

# List all stashed files
alias gsl='git stash list'

# Pop the last changes off the stash
alias gsp='git stash pop'

# Show a stashed item
#   '-p' makes it more like 'git show'
#   use with 'stash@{n}' to reference a particular stash item
alias gss='git stash show -p'

# Drop a stash item, latest by default and specify with 'stash@{n}'
alias gsd='git stash drop'

# Git Grep for a list of files that contain the string
alias ggno='git grep --name-only'

# Git grep for files that contain string and open them in vim
alias ggo='git_grep_open'


# -- Ruby Aliases --
# Run Rubocop gem
alias rbc='rubocop'

# Run Rubocop gem and autocorrect detected violations when available
alias rbca='rubocop --auto-correct'

# Bundle exec
alias be='bundle exec'

# Bundle exec rake shortcut
alias ber='bundle exec rake'

# Bundle exec rspec
alias be-rspec='bundle exec rspec'

# Runs rubocop with all of the changed files
alias rbc-m="git_show_exclude_ruby_files | xargs rubocop"

# Runs rubocop with autocorrect, (-n1) once for each file,
#   and (-p) while asking permission.
alias rbca-m="git_show_exclude_ruby_files | xargs -n1 -p rubocop --auto-correct"

# Run migrations
alias db-migrate="bundle exec rake db:migrate && RACK_ENV=test bundle exec rake db:migrate"


# -- Other Aliases
alias ..='cd ..'         # Go up one directory
alias ...='cd ../..'     # Go up two directories
alias ....='cd ../../..' # Go up three directories
alias -- -='cd -'        # Go back

# Provide a config file to yamllint
alias yamllint='yamllint -c $HOME/.yamllint'

# Run the last command as sudo
alias ok='sudo $(fc -ln -1)'

# Open changed files in (m)vim
alias mvim-gd='mvim $(git diff --name-only)'
alias vim-gd='vim $(git diff --name-only)'

# Identify image properties for gifs
alias igif='identify -format "%f[%s] canvas=%Wx%H size=%wx%h offset=%X%Y %D %Tcs\n"'
