#!/usr/bin/env zsh
# vi: ft=zsh

# Info on how to write completions
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org

# Enable zsh-completions from brew
fpath=(/usr/local/share/zsh-completions $fpath)

# Enable custom completions for my functions
fpath=(~/.zsh/functions/completions/ $fpath)

# The following lines were added by compinstall
zstyle :compinstall filename '/Users/trentscheffert/.zshrc'

autoload -Uz compinit && compinit
# End of lines added by compinstall

# Set completion functions that are used.
#   On the first run use the fast ones, if completion is called a second time then
#   use the slow ones. Alternate back and forth on subsequent invocations.
#   See 'Control Functions' in 'COMPLETION SYSTEM CONFIGURATION' (in zshall) for more details
zstyle -e ':completion:*' completer '
if [[ $_last_completion_try != "$HISTNO$BUFFER$CURSOR" ]]; then
  _last_completion_try="$HISTNO$BUFFER$CURSOR"
  reply=(_complete _match _prefix _expand)
else
  _last_completion_try=null
  reply=(_ignored _correct _approximate)
fi'

# TODO: http://zsh.sourceforge.net/Guide/zshguide06.html#l144

# TODO: Replace these
# Add tab completion for many Bash commands
# if which brew > /dev/null && [ -f "$(brew --prefix)/etc/bash_completion" ]; then
# 	source "$(brew --prefix)/etc/bash_completion";
# elif [ -f /etc/bash_completion ]; then
# 	source /etc/bash_completion;
# fi;

# # Enable tab completion for `g` by marking it as an alias for `git`
# if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
# 	complete -o default -o nospace -F _git g;
# fi;

# # Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
# [ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2 | tr ' ' '\n')" scp sftp ssh;

# TODO:
# Do I want any completions? https://github.com/Bash-it/bash-it/tree/master/completion/available
