#!/usr/bin/env zsh
# vi: ft=zsh

# -- Keybinds --
# Use emacs mode for now
bindkey -e # for emacs

# --- Functions ---

# Set out functions to autoload
fpath=(~/.zsh/functions $fpath)
autoload -U ~/.zsh/functions/*(.:t)

fpath=(~/.zsh/functions/psql $fpath)
autoload -U ~/.zsh/functions/psql/*(.:t)

fpath=(~/.zsh/functions/kafka $fpath)
autoload -U ~/.zsh/functions/kafka/*(.:t)

fpath=(~/.zsh/functions/ruby $fpath)
autoload -U ~/.zsh/functions/ruby/*(.:t)


# -- History --
function _setup_history() {
  # if history directory doesn't exist, make it
  local directory=~/.zsh_history/
  if [[ ! -d "$directory" ]]; then
    mkdir "$directory"
  fi

  local date=$(date +%Y-%m-%d) # yyyy-mm-dd format
  local file="$directory.zsh_history-$date"

  # Set history file to something different every day
  HISTFILE="$file"

  # History lines in memory
  HISTSIZE=10000
  # History lines on disk
  SAVEHIST=1000000
}

_setup_history


# --- Options ---
# TODO: More from http://zsh.sourceforge.net/Guide/zshguide02.html#l13
# TODO: Good ones here too http://askubuntu.com/questions/1577/moving-from-bash-to-zsh

# Options from the zsh-newusuer-install
setopt notify
unsetopt autocd extendedglob

# Autocompletion of command line switches for aliases
setopt completealiases

# Don't beep if you're angry
setopt nobeep

# Enable gco='git-checkout' aliasing
setopt no_complete_aliases


# -- Expansion and Globbing Options

# Print a warning message when a global parameter is created in a function
#   by an assignment
setopt warn_create_global

# If a pattern for filename generation has no matches print an error instead of
#   leaving it unchanged in the argument list.
setopt no_match

# If a pattern for filename generation is badly formed print an error
setopt bad_pattern


# -- History Options --

# Append commands to the history file after once they've finished executing
setopt INC_APPEND_HISTORY_TIME

# Ignore duplicated sequential lines in the history
setopt HIST_IGNORE_DUPS

# Save timestamps (in epoch) and duration (in seconds) in history as well
#   Format: ': <beginning time>:<elapsed seconds>;<command>'
setopt EXTENDED_HISTORY

# Remove unimportant blanks
setopt HIST_REDUCE_BLANKS

# Don't beep if we reach the end of history
setopt NO_HIST_BEEP


# Autoloaded functions from files are wrapped in functions rather than just
#   containing the body of the function
# TODO: This breaks zsh/prompt autoloading for whatever reason, we can't autoload colors then
# setopt KSH_AUTOLOAD

# TODO: Replace these
# # Case-insensitive globbing (used in pathname expansion)
# shopt -s nocaseglob;

# # Bash checks the window size after each command and, if necessary, updates the values of LINES and COLUMNS
# shopt -s checkwinsize

# # Autocorrect typos in path names when using `cd`
# shopt -s cdspell;


# --- Help ---
# From the brew zsh caveats, enables access to the online help
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help
