#!/usr/bin/env zsh
# vi: ft=zsh

# Config for working at Echo

# --- Path ---

# --- Aliases ---

# --- Exports ---

export DEVTOOLS_LOGGER_FORMAT=clean

# Set up KUBECONFIG for multiple kubectl config files by extending existing KUBECONFIG,
# which is a list of kubectl config files

function append_to_kubeconfig {
  local server=${1:?Must pass server to append}

  if [[ ! -f "$server" ]]; then
    echo 1>&2 "Kubectl config file '$server' doesn't exist"
    return 1
  fi

  if [[ -n "$KUBECONFIG" ]]; then
    if [[ "$KUBECONFIG" =~ "$server" ]]; then
      export KUBECONFIG="$KUBECONFIG"
    else
      # Supposedly semi-colon separated on windows, colon everywhere else but I
      # only got it working with a colon in my zsh on windows shell. Maybe I will
      # need a semi-colon for Powershell?
      export KUBECONFIG="$KUBECONFIG:$server"
    fi
  else
    export KUBECONFIG="$server"
  fi
}

# append_to_kubeconfig "$HOME/.kube/config-dev-k8smaster1"
# append_to_kubeconfig "$HOME/.kube/config-qa1-k8smaster1"
# append_to_kubeconfig "$HOME/.kube/config-prd-k8smaster1"
# append_to_kubeconfig "$HOME/.kube/config-tk-k8smaster1"
