#!/usr/bin/env zsh
# vi: ft=zsh

# --- CONFIG ---

# Make vim the default editor
export EDITOR="vim";

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# Use 'less' as the pager
export PAGER='less'

# Prefer exact matching to fuzzy finding when searching history
export FZF_CTRL_R_OPTS='--exact'

# Options for LESS are read from here the $LESS variable
#   --IGNORE-CASE: Ignore case in searches, even if the search contains a capital letter
#   --quit-if-one-screen: Automatically exit if entire file can be
#     displayed on one screen
#   --hilite-search: When searching, only highlight last matched string
#     instead of all matches
#   --RAW-CONTROL-CHARS: Ouput ANSI color escape sequences in "raw" form
#   --jump-target=.2: Jumps (including search) end at the specified line or
#     percentage of the screen
#   --status-column: Displays a status column at the left edge of the screen which
#     shows the lines that matched the current search.
#   --HILITE-UNREAD: Temporarily highlights the first "new" line after a forward
#     movement larger than one page.
# local less_opts=''
# NOTE: Git sets "-FRX" by default, so if we want to preserve git behavior we need those
local less_opts='--IGNORE-CASE'
less_opts+=' --quit-if-one-screen'
less_opts+=' --hilite-search'
less_opts+=' --RAW-CONTROL-CHARS'
less_opts+=' --jump-target=.4'
less_opts+=' --status-column'
less_opts+=' --HILITE-UNREAD'
export LESS="$less_opts"

# Colorful Less!
# Source:
#   http://www.tuxarena.com/2012/04/tutorial-colored-man-pages-how-it-works/
#   https://unix.stackexchange.com/questions/108699/documentation-on-less-termcap-variables
# TODO: Get this working, right now it screws up `env`
# export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode - red
# export LESS_TERMCAP_md=$(printf '\e[01;35m') # enter double-bright mode - bold, magenta
# export LESS_TERMCAP_me=$(printf '\e[0m') # turn off all appearance modes (mb, md, so, us)
# export LESS_TERMCAP_se=$(printf '\e[0m') # leave standout mode
# export LESS_TERMCAP_so=$(printf '\e[01;33m') # enter standout mode - yellow
# export LESS_TERMCAP_ue=$(printf '\e[0m') # leave underline mode
# export LESS_TERMCAP_us=$(printf '\e[04;36m') # enter underline mode - cyan

# Ruby settings for a faster test!
export RUBY_GC_HEAP_INIT_SLOTS=1000000
# export RUBY_GC_HEAP_FREE_SLOTS=1000000 # Another good one to check out
export RUBY_GC_MALLOC_LIMIT=1000000000
# export RUBY_GC_MALLOC_LIMIT_MAX=1000000000 # Another good one to investigate
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_HEAP_FREE_MIN=500000

# Set the default external encoding to utf-8, always
if [[ -n "$RUBYOPT" ]]; then
  # Extend existing RUBYOPT, which is a space separated of commandline flags
  if [[ "$RUBYOPT" =~ "-E*" ]]; then
    # Seems we've already set the -E flag, no changes
    export RUBYOPT="$RUBYOPT"
  else
    export RUBYOPT="$RUBYOPT -Eutf-8"
  fi
else
  export RUBYOPT='-Eutf-8'
fi


export INPUTRC=~/.inputrc

# --- PATH ---
prepend_to_path "$HOME/bin"
