#!/usr/bin/env zsh
# vi: ft=zsh

# --- Path ---

# Set up the manpath
initialize_osx_manpath

# Find man files for 'coreutils'
manpath=('/usr/local/opt/coreutils/libexec/gnuman' $manpath)

# Man files for 'findutils'
manpath=('/usr/local/opt/findutils/libexec/gnuman' $manpath)

# Man files for 'gnu-tar'
manpath=('/usr/local/opt/gnu-tar/libexec/gnuman' $manpath)


# --- Prepend ---

# For homebrewed 'coreutils'
prepend_to_path '/usr/local/opt/coreutils/libexec/gnubin'

# For homebrewed 'findutils'
prepend_to_path '/usr/local/opt/findutils/libexec/gnubin'

# For homebrewed 'gnu-tar'
prepend_to_path '/usr/local/opt/gnu-tar/libexec/gnubin'

# Brew Doctor told me to add this because I have utilities that put things here
prepend_to_path '/usr/local/sbin'


# --- Exports ---

# Make MacVim the default visual editor.
#   '-f' tells it not to fork a new process. Works better with shell.
export VISUAL='mvim -f'

# Install to global /Applications, not user local ~/Applications
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Set the required env variable for postgres
export PGDATA='/usr/local/var/postgres'
export PGGHOST=localhost

# Android from `brew install android-sdk`
export ANDROID_HOME='/usr/local/opt/android-sdk'


# --- Aliases ---

# Hide/Show dot prefaced files in finder
#   Source: http://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/
alias finder-show-hidden-files='defaults write com.apple.finder AppleShowAllFiles YES; \
  killall Finder /System/Library/CoreServices/Finder.app'
alias finder-hide-hidden-files='defaults write com.apple.finder AppleShowAllFiles NO; \
  killall Finder /System/Library/CoreServices/Finder.app'

# Reload karabiner after config updates
# Source: https://karabiner-elements.pqrs.org/docs/manual/misc/configuration-file-path/
alias restart-karabiner='launchctl kickstart -k gui/`id -u`/org.pqrs.karabiner.karabiner_console_user_server'


# --- Functions ---
if [[ -d "~/.zsh/functions/macos" ]]; then
  fpath=(~/.zsh/functions/macos $fpath)
  autoload -U ~/.zsh/functions/macos/*(.:t)
fi


# --- Ruby ---
# Rbenv was installed with homebrew, the paths will be osx specific

#  1. Sets up shims path, based on RBENV_ROOT
#  2. Installs autocompletion for zsh
#  3. Rehashes shims, which makes sure they're all up to date
#  4. Installs the sh dispatcher which enables stuff
if which rbenv > /dev/null ; then
  # Use Homebrew's directories rather than ~/.rbenv
  export RBENV_ROOT=/usr/local/var/rbenv

  eval "$(rbenv init - zsh)"
fi


# --- Node ---
# nvm installed with homebrew too
# Set up NVM
# TODO: Resolve the "scalar parameter CONSTANT_VALUE created globally in function" warning
# Only run if nvm installed
if [[ -d "~/.nvm"  ]]; then
  export NVM_DIR=~/.nvm

  function init_nvm() {
    source $(brew --prefix nvm)/nvm.sh
  }
fi


# --- Colorful LS ---
# Good examples:
#   https://github.com/Bash-it/bash-it/blob/master/lib/appearance.bash
#   http://altoidnerd.com/2015/10/06/using-ls_colors-to-colorize-your-shell-by-filename-filetype/

# LS_COLORS for non-GNU systems (BSD) (from: http://geoff.greer.fm/lscolors/)
export CLICOLOR=1
export LSCOLORS=ExFxdxdxcxacaccxxxExEh

# LS_COLORS helper for GNU systems
#   requires /gnubin in the path already
eval "$(dircolors ~/.dir_colors)"

# Zsh completion can use LS_COLORS too!
zstyle ':completion:*:default' list-colors "${(@s.:.)LS_COLORS}"

# TODO: Grep colors too
# if echo hello | grep --color=auto l >/dev/null 2>&1; then
#   export GREP_OPTIONS='--color=auto'
#   export GREP_COLOR='0;32'
#   export GREP_COLORS="sl=0;37:cx=1;32:mt=1;35:fn=0;32:ln=1;34:se=1;33"
# fi


# --- Go ---
# Add GOROOT-based install location to path
# append_to_path '/usr/local/opt/go/libexec/bin'

# This is where of the depedencies and such
if [[ ! -d ~/go ]]; then
  mkdir ~/go
fi
export GOPATH="$HOME/go"

# Add golang tooling that I download to the path
append_to_path "$GOPATH/bin"


# --- Docker-Machine ---
function docker_machine_running() {
  docker-machine ip >/dev/null 2>&1
}

if docker_machine_running; then
  eval $(docker-machine env)
fi
