#!/usr/bin/env zsh
# vi: ft=zsh

# --- Path ---

# -- Prepend --

# Clearly we want vim...
prepend_to_path 'C:\Program Files\Vim\vim80'


# -- Append --

# We want IIS Express!
append_to_path 'C:\Program Files (x86)\IIS Express\'

# Adb for android debugging
# append_to_path 'C:\Users\tscheffert\AppData\Local\Android\android-sdk\platform-tools'

# Python Scripts including pip
append_to_path 'C:\tools\python\Scripts'

# Xmllint from libxml2
append_to_path 'C:\tools\xmllint'

# Add ConEmuBaseDir to the path for csudo.cmd
append_to_path '$ConEmuBaseDir'

# Git repo encryption utility
append_to_path 'C:\Projects\github\elasticdog\transcrypt'


# --- Aliases ---

alias 'csudo'='csudo.cmd'

# TODO: This works with `open .` but not `open /path/to/place` :*(
alias 'open'='start'

# TODO: Maybe set up in function files like I have other stuff?
# TODO: Get this working
# function explorer() {
#   local destination = "$@"
#   if [[ $@ == '' ]]; then
#     destination="./"
#   fi
#   explorer.exe "$(to_windows_path $destination)"
# }

alias 'powershell_split'='ConEmu64 -run powershell -new_console:asV'

# -- PowerShell Aliases/Functions --
function ps-lint() {
  # Invoke the PSScriptAnalyzer, which is installed via PowerShell Gallery
  powershell -Command "Invoke-ScriptAnalyzer -Path $1"
}

function ps-beautify() {
  # Invoke the beautify function defined in my PowerShell profile
  powershell -Command "Edit-BeautifyFile $1"
}


# --- Exports ---

# Uncomment these when trying to install native extensions for ruby gems that fail
# export tmp="$(cygpath -m "/tmp")"
# export TMP="$(cygpath -m "$TMP")"
# export TEMP="$(cygpath -m "$TEMP")"
# export TMPDIR="$(cygpath -m "$TMPDIR")"
