#!/usr/bin/env zsh
# vi: ft=zsh

# --- Path ---


# -- Prepend --
prepend_to_path "$HOME/.rbenv/bin"


# -- Append --


# --- Aliases ---
alias 'update-wsl'='sudo apt-get update && sudo apt-get upgrade'


# --- Ruby ---
if which rbenv > /dev/null ; then
  eval "$(rbenv init - zsh)"
fi
