#!/usr/bin/env zsh
# vi: ft=zsh

function knife_upload_vault() {
  local vault_name="$1"
  if [[ -z "$vault_name" ]]; then
    echo 1>&2 "No vault name passed"
    local failed=true
  fi

  local target_server="$2"
  if [[ -z "$target_server" ]]; then
    echo 1>&2 "No target server specified"
    local failed=true
  fi

  if [[ ! -d "./data_bags/chef_vault/" ]]; then
    echo 1>&2 "Working directory must be at the root of the chef-repo"
    local failed=true
  fi

  local target_vault_file="./data_bags/chef_vault/$vault_name.key"
  if [[ ! -f "$target_vault_file" ]]; then
    echo 1>&2 "Target vault file $target_vault_file doesn't exist"
    local failed=true
  fi

  case "$target_server" in
    sandbox)
      if [[ -z "$CHEF_KNIFE_SANDBOX_CONFIG" ]]; then
        echo 1>&2 "Must export \$CHEF_KNIFE_SANDBOX_CONFIG"
        local failed=true
      else
        local knife_config="$CHEF_KNIFE_SANDBOX_CONFIG"
      fi
      ;;
    live)
      if [[ -z "$CHEF_KNIFE_LIVE_CONFIG" ]]; then
        echo 1>&2 "Must export \$CHEF_KNIFE_LIVE_CONFIG"
        local failed=true
      else
        local knife_config="$CHEF_KNIFE_LIVE_CONFIG"
      fi
      ;;
    *)
      echo 1>&2 "Target server must be one of sandbox|live"
      local failed=true
      ;;
  esac

  if [[ $failed ]]; then
    echo 1>&2 "\nUsage:"
    echo 1>&2 "  knife_upload_vault {vault_name} {target_server}"
    echo 1>&2 "  - vault_name: The vault name that you wish to upload, like development, qa, or production"
    echo 1>&2 "  - target_server: The server to upload the cookbook to, one of sandbox|live"
    return 1
  fi

  knife vault update chef_vault "$vault_name" --mode client --json "$target_vault_file" --config "$knife_config"
}

