#!/usr/bin/env zsh
# vi: ft=zsh

function knife_show_cookbook() {
  local cookbook_name="$1"
  if [[ -z "$cookbook_name" ]]; then
    echo 1>&2 "No cookbook name passed"
    local failed=true
  fi

  local target_server="$2"
  if [[ -z "$target_server" ]]; then
    echo 1>&2 "No target server specified"
    local failed=true
  fi

  case "$target_server" in
    sandbox)
      if [[ -z "$CHEF_KNIFE_SANDBOX_CONFIG" ]]; then
        echo 1>&2 "Must export \$CHEF_KNIFE_SANDBOX_CONFIG"
        local failed=true
      else
        local knife_config="$CHEF_KNIFE_SANDBOX_CONFIG"
      fi
      ;;
    live)
      if [[ -z "$CHEF_KNIFE_LIVE_CONFIG" ]]; then
        echo 1>&2 "Must export \$CHEF_KNIFE_LIVE_CONFIG"
        local failed=true
      else
        local knife_config="$CHEF_KNIFE_LIVE_CONFIG"
      fi
      ;;
    *)
      echo 1>&2 "Target server must be one of sandbox|live"
      local failed=true
      ;;
  esac

  if [[ $failed ]]; then
    echo 1>&2 "\nUsage:"
    echo 1>&2 "  knife_show_cookbook {cookbook_name} {target_server}"
    echo 1>&2 "  - cookbook_name: The cookbook name that you wish to upload, like app_deadbolt or role_common_app"
    echo 1>&2 "  - target_server: The server to upload the cookbook to, one of sandbox|live"
    return 1
  fi

  knife cookbook show "$cookbook_name" --config "$knife_config"
}

